services:
  postgres:
    image: postgres:18-alpine
    container_name: eac-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eac-network
  #  ocr-server:
  #    build:
  #      context: ./ocr-server
  #    image: ocr-server:latest
  #    ports:
  #      - "9003:9003"
  #    networks:
  #      - eac-network
  backend:
    image: eclipse-temurin:25-jre-ubi10-minimal
    container_name: eac-backend
    depends_on:
      - postgres
    #      - ocr-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_KEY
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    command: sh -c "cd /app/backend/app && java -Dspring.aot.enabled=true -jar app.jar"
    networks:
      - eac-network
  frontend:
    image: caddy:2.11-alpine
    container_name: eac-frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/conf/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/cert:/data/caddy
      - ./frontend/html:/usr/share/caddy:ro
    networks:
      - eac-network
    restart: always
volumes:
  pgdata:
networks:
  eac-network:
    driver: bridge
