services:
  postgres:
    image: postgres:18-alpine
    container_name: eac-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  #  ocr-server:
  #    build:
  #      context: ./ocr-server
  #    image: ocr-server:latest
  #    ports:
  #      - "9003:9003"
  #    networks:
  #      - eac-network
  backend:
    image: alpine:3.23.3
    container_name: eac-backend
    depends_on:
      postgres:
        condition: service_healthy
    #      - ocr-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file:
      - .env
    volumes:
      - ./backend-go:/app/backend
    command: sh -c "cd /app/backend/ && ./backend-go"
  frontend:
    image: caddy:2.11-alpine
    container_name: eac-frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/conf/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/cert:/data/caddy
      - ./frontend/html:/usr/share/caddy:ro
volumes:
  pgdata:
